# Solved
# Even Fibonacci Numbers

# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.
# Answer: 4613732


# Solution:

firstNum = 0
secondNum = 1
currentNum = 0
total_sum = 0

while currentNum <= 4000000:
    currentNum = firstNum + secondNum
    if currentNum % 2 == 0:
        total_sum += currentNum
    firstNum = secondNum
    secondNum = currentNum
print(total_sum)